### ISSUE TITLE
[TODO] 下拉框选择内部地图

### ISSUE THREAD

**Issue by msojocs** [msojocs/AutoRun#3]
支持龙泉地图选择

**Comment by yanyaoli** [comment]
最后能否增加一个runInfo信息，返回runValidDistance和runValidCount数据 :heart_eyes:

**Comment by msojocs** [comment]
> 最后能否增加一个runInfo信息，返回runValidDistance和runValidCount数据 😍

这是哪里的数据

**Comment by yanyaoli** [comment]
> > 最后能否增加一个runInfo信息，返回runValidDistance和runValidCount数据 😍
> 
> 
> 
> 这是哪里的数据

Get: https://run-lb.tanmasports.com/v1/unirun/query/runInfo?userId=12345&yearSemester=20232

Headers: 
Host: run-lb.tanmasports.com
Content-Type: application/json
appKey: appKey
Accept-Encoding: 
Connection: 
Accept: application/json
User-Agent: 
Accept-Language: 
token: token
sign: sign

Response Body:
{
  "msg" : "成功",
  "response" : {
    "runValidDistance" : 67257,
    "semesterId" : 229365,
    "schoolId" : 3680,
    "runDistance" : 97728,
    "runDay" : 16,
    "runCalorie" : 6074762,
    "runCount" : 21,
    "userId" : 123456,
    "createTime" : "2023-09-03 22:44:01",
    "runValidCount" : 16,
    "infoStatus" : "1",
    "runValidCalorie" : 0,
    "yearSemester" : 20232,
    "studentId" : 654321,
    "runValidDay" : 16
  },
  "code" : 10000
}

**Comment by yanyaoli** [comment]
> > 最后能否增加一个runInfo信息，返回runValidDistance和runValidCount数据 😍
> 
> 
> 
> 这是哪里的数据

Get: https://run-lb.tanmasports.com/v1/unirun/query/runInfo?userId=123456&yearSemester=20232

Headers:
Host: run-lb.tanmasports.com
Content-Type: application/json
appKey: appKey
Accept-Encoding:
Connection:
Accept: application/json
User-Agent:
Accept-Language:
token: token
sign: sign

Response Body:
{
"msg" : "成功",
"response" : {
"runValidDistance" : 67257,
"semesterId" : 229365,
"schoolId" : 3680,
"runDistance" : 97728,
"runDay" : 16,
"runCalorie" : 6074762,
"runCount" : 21,
"userId" : 123456,
"createTime" : "2023-09-03 22:44:01",
"runValidCount" : 16,
"infoStatus" : "1",
"runValidCalorie" : 0,
"yearSemester" : 20232,
"studentId" : 654321,
"runValidDay" : 16
},
"code" : 10000
}

**Comment by solisdj2** [comment]
怎么用的啊？
